AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSHttpProxy

  Sample SAM Template for AWSHttpProxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  HttpProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HttpProxyFunction
      Handler: com.tibell.infra.httpproxy.AWSHttpProxyApp::handleRequest
      Runtime: java21
      Architectures:
        - arm64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HttpProxy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HttpProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for HttpProxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HttpProxyFunction:
    Description: "HttpProxy Lambda Function ARN"
    Value: !GetAtt HttpProxyFunction.Arn
  HttpProxyFunctionIamRole:
    Description: "Implicit IAM Role created for HttpProxy function"
    Value: !GetAtt HttpProxyFunctionRole.Arn
